[project]
name = "kohai"
version = "0.4.0"
description = "Interactive anime browser and player for the terminal"
readme = "README.md"
authors = [
    { name = "dity", email = "275731998+dity42@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anime-parsers-ru>=1.18.0",
    "pyfzf>=0.3.1",
]

[project.scripts]
kohai = "kohai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
